# Generated by Django 5.2.8 on 2025-11-16 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterAPI', '0003_alter_user_phone_num_alter_user_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iamge',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='expire_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to=settings.AUTH_USER_MODEL),
        ),
    ]
